apiVersion : apps/v1
kind : Deployment
metadata : 
  name : springboot-welcome-deployment
  labels :
    app : welcome
spec :
  replicas : 1
  selector : 
    matchLabels :
      app : welcome
  template :
    metadata:
      labels:
        app : welcome
    spec:
      containers:
      - name : welcome-pod
        image : bhavani005/springboot-welcome
        ports :
        - containerPort : 80 
---
apiVersion : v1
kind : Service
metadata:
  name : springboot-welcome-service
spec:
  selector :
    app : welcome
  ports :
    - protocol : TCP 
      port : 8081
      targetPort : 80
      nodePort : 30008
  type : LoadBalancer
